### PR TITLE
Add nicehash.ps1 to balances for GUI

### PR DESCRIPTION
**Pull request by JimKnightster**
requires API_ID and API_KEY to Nicehash config

### CODE REVIEW

**Comment by grantemsley** [comment]
Awesome you figured out pull requests!  I will be testing this tomorrow.

**Comment by grantemsley** [comment]
Do you actually need to do both API calls?

It looks like just the public one does return all the necessary balance information (though you do have to add up the algorithms separately).

I don't even have an account on nicehash I just mine to my own address, so no API keys, so I can't test what the private API call returns, but I don't think it's needed.

**Comment by grantemsley** [comment]
I modified this to not require the API keys - just the address is sufficient to get outstanding balance.  It's in my fork now.

Thanks again for your help.

**Comment by JimKnightster** [comment]
No problem, but I think without the API keys you only get outstanding balance (nothing thats in the NH wallet will show up.  It just shows the algos that have a balance in them that have not been transferred to the wallet (internal or external), that is why I put both of them in there.  At least that is my understanding, I am about .0004 short to see if it is true.

**Pull request closed without merging**
